dataname: ASL-Citizen-confidence-0.9
_target_: datamodule.SMPLXDataModule

# Paths
data_path: ${path.datasets}/ASL_citizen_confidence_0.9
split_path: ${path.datasets}/ASL_citizen_confidence_0.9

# Text

# Machine
# batch_size: ${}data

batchsize: ${server.batch_size}
num_workers: ${server.num_workers}
data_dir: ""
sampler: ${sampler}
defaults:
  - /transforms.yaml@transforms