_target_: model.losses.temos_loss.TemosComputeLoss
# loss terms
## Reconstruction loss
lmd_rfeats_recons: 1.0

## Latent sapces losses
lmd_latent: 1.0e-5
lmd_kl: 1.0e-5


# Ablations
loss_on_both: true
foce_loss_on_jets: false
ablation_no_kl_conmbine: false
ablation_no_kl_gaussian: false
ablation_no_motionencoder: false

recons_text2rfeats: ${.lmd_rfeats_recons}
recons_text2rfeats_func: ${model.func_recons}

recons_rfeats2rfeats: ${.lmd_rfeats_recons}
recons_rfeats2rfeats_func: ${model.func_recons}

# Latent space losses
latent_manifold: ${.lmd_latent}
latent_manifold_func: ${model.func_latent}

# VAE losses
kl_text: ${.lmd_kl}
kl_text_func: ${model.func_kl}

kl_motion: ${.lmd_kl}
kl_motion_func: ${model.func_kl}

kl_text2motion: ${.lmd_kl}
kl_text2motion_func: ${model.func_kl}

kl_motion2text: ${.lmd_kl}
kl_motion2text_func: ${model.func_kl}